spring:
  application:
    name: covid-test-mgt
  security:
    oauth2:
      resourceServer:
        jwt: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_o9PK57x2H


      # client:
      #   registration:
      #     cognito:
      #       client-id: #TODO
      #       client-secret: #TODO
      #       scope: openid
      #       redirect-uri: http://localhost:8080/login/oauth2/code/cognito
      #       clientName: #TODO
      #   provider:
      #     cognito:
      #       # issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_VPtaZ52VU/
      #       issuerUri: #TODO
      #       user-name-attribute: cognito:username
